/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WrapperBIMJava */

#ifndef _Included_WrapperBIMJava
#define _Included_WrapperBIMJava

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WrapperBIMJava
 * Method:    displayHelloWorld
 * Signature: ()V
 * 
 * // Convert the C style string to a basic_string and display it.
 *   string basicstring(orig);
 *   basicstring += " (basic_string)";
 *   cout << basicstring << endl;
 */
JNIEXPORT jint JNICALL Java_WrapperBIMJava_callWrapperRead(JNIEnv *jn, jobject jobj, jstring mystring);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WrapperBIMJava
 * Method:    displayHelloWorld
 * Signature: ()V
 */
	JNIEXPORT jstring JNICALL Java_WrapperBIMJava_callWrapperGetHeaderDescription(JNIEnv *jn, jobject jobj);

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     WrapperBIMJava
	* Method:    displayHelloWorld
	* Signature: ()V
	*/
	JNIEXPORT jstring JNICALL Java_WrapperBIMJava_callWrapperGetHeaderFileName(JNIEnv *jn, jobject jobj);

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     WrapperBIMJava
	* Method:    displayHelloWorld
	* Signature: ()V
	*/
	JNIEXPORT jstring JNICALL Java_WrapperBIMJava_callWrapperGetHeaderSchema(JNIEnv *jn, jobject jobj);

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     WrapperBIMJava
	* Method:    displayHelloWorld
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_WrapperBIMJava_callWrapperExit(JNIEnv *jn, jobject jobj);

#ifdef __cplusplus
}
#endif

#endif
